---
- vsphere_guest:
    vcenter_hostname: 192.168.1.207
    username: administrator@vsphere.local
    password: "{{ vcenter_password }}"
    guest: "{{ vm_name }}"
    vmware_guest_facts: yes

- wait_for:
    delay: 60