---
- name: Force node offline
  bigip_node:
      server: "{{ server }}"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "enabled"
      monitor_state: "enabled"
      partition: "Common"
      host: "{{ member_name }}"
      name: "{{ member_name }}"