---
- name: Install java
  yum:
    name: java
    state: installed

- name: Update Java permissions
  file:
    path=/opt
      owner=root group=root recurse=yes mode=0755

- name: Create temporary java answers file
  copy: src=answers dest=/tmp/answers mode=0644

- name: Delete java answers file
  file: path=/tmp/answers state=absent

- name: Delete temporary java files
  file: path=/tmp/jdk1.8.0_102 state=absent
  ignore_errors: yes

- name: Setup Java (EL)
  shell: /usr/sbin/alternatives --install /usr/bin/java java /opt/jdk1.8.0_102/bin/java 5

- name: Configure java (EL)
  shell: /usr/sbin/alternatives --set java /opt/jdk1.8.0_102/bin/java

- name: add group "tomcat"
  group: name=tomcat

- name: add user "tomcat"
  user: name=tomcat group=tomcat home=/usr/share/tomcat createhome=no
  become: True
  become_method: sudo

- name: Install Tomcat Server
  yum:
    name: tomcat
    state: installed

- name: Creates directory
  file: path=/usr/share/tomcat/conf state=directory

- name: Change ownership of Tomcat installation
  file: path=/usr/share/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

- name: Configure Tomcat server
  template: src=server.xml dest=/usr/share/tomcat/conf/

- name: Configure Tomcat users
  template: src=tomcat-users.xml dest=/usr/share/tomcat/conf/

- name: Install Tomcat init script
  copy: src=tomcat-initscript.sh dest=/etc/init.d/tomcat mode=0755

- name: deploy iptables rules
  template: src=iptables-save dest=/etc/sysconfig/iptables

- name: sample app
  copy: src=sample.war dest=/var/opt/pivotal/pivotal-tc-server-standard/myserver/webapps/sample.war

