---
- name: Copy file
    cisco_file_transfer:
    source_file: "/var/lib/awx/projects/_100__my_ansible_playbooks/mayo/roles/ciscocopy/vars/ciscolog.txt"
    dest_file: ciscolog.txt
    enable_scp: true
    provider: '{{ cli }}'
