---
- name: Show Version and Show interfaces
  ios_command:
    host: "{{ inventory_hostname }}"
    commands:
      - show ip interface brief
    wait_for:
      - result [0] contains FastEthernet1/0/15