---
- name: Force node offline
  bigip_node:
      server: "192.168.1.140"
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "disabled"
      monitor_state: "disabled"
      partition: "Common"
      host: "192.168.1.142"
      name: "Test_server1"
