---
- hosts: all
  gather_facts: False
  connection: local

  roles:
   - { role: junosacl, when: "device_os == 'junos'" }
   - { role: ciscoacl, when: "device_os == 'iosxr'" }
   - { role: aristaacl, when: "device_os == 'eos'" }
