---
- name: register variable
  nxos_command:
    commands: show running-config
    host: "{{ inventory_hostname }}"
#    provider: "{{ cli }}"
  register: config

- name: get current configured ntp servers
  set_fact: _servers="{{ config | regex_findall('^ntp server (\S+) use-vrf (?!management)') }}"

- name: remove old ntp servers
  nxos_config:
    lines:
      - "no ntp server {{ item }}"
    provider: "{{ provider }}"
    force: yes
  with_items: "{{ _servers }}"

- name: add ntp servers
  nxos_config:
    host: '{{ inventory_hostname }}'
    transport: cli
    lines:
      - ntp server 172.16.1.200
      - ntp server 172.16.1.177