---
- name: register variable
  nxos_command:
    commands: show running-config
    host: "{{ inventory_hostname }}"
#    provider: "{{ cli }}"
  register: config

- name: Default NTP
  nxos_config:
    host: '{{ inventory_hostname }}'
    lines: no {{ item }}
    with_items: "{{ config_lines | select('match', 'ntp *') | list }}"

- name: add ntp servers
  nxos_config:
    host: '{{ inventory_hostname }}'
    transport: cli
    lines:
      - ntp server 172.16.1.200
      - ntp server 172.16.1.177