---
- name: Show Version and Show interfaces
  ios_command:
    run_once: true
    delegate_to: 192.168.1.175
    host: "{{ inventory_hostname }}"
    username: "{{ cisco_user }}"
    password: "{{ cisco_password }}"
    commands:
      - show version
      - show ip interface brief
      - show run

