---
- name: get current configured ntp servers
  set_fact: _servers="{{ config | regex_findall('^ntp server (\S+) use-vrf (?!management)') }}"

- name: remove old ntp servers
  nxos_config:
    lines:
      - "no ntp server {{ item }}"
    provider: "{{ provider }}"
    force: yes
  with_items: "{{ _servers }}"

- name: Show Version and Show interfaces
  nxos_command:
    host: "{{ inventory_hostname }}"
    commands:
      - show version
      - show ip interface brief
      - show run
