---
- name: Force node offline
  bigip_node:
      server: "{{ loadbalancer}} "
      user: "{{ user }}"
      password: "{{ password }}"
      state: "present"
      session_state: "disabled"
      monitor_state: "disabled"
      partition: "Common"
      name: "{{ node }}"