---
- name: Force node offline
  bigip_node:
      server: "{{ server }}"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "disabled"
      monitor_state: "disabled"
      partition: "Common"
      name: "{{ name }}"
