---
- name: Force node offline
  bigip_node:
      state: "present"
      user: "{{ user }}"
      password: "{{ password }}"
      session_state: "disabled"
      monitor_state: "disabled"
      partition: "Common"
      name: "{{ name }}"
      host: "{{ host }}"