---
- name: configure interface settings
  nxos_config:
    src: "{{ playbook_dir }}/backup/{{ inventory_hostname }}/running-config"
    host: "{{ inventory_hostname }}"
    match: strict
#    provider: "{{ cli }}"
